--- #YAML:1.0
name:               Catalyst-Helper-InitScript-FreeBSD
version:            0.01
abstract:           /usr/local/etc/rc.d/yourapp.sh generator.
author:
    - Tomohiro Hosaka <bokutin@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Term::Prompt:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
